changelog:
    exclude:
        labels:
            - chore
            - style
    authors:
      - NexusWave

    categories:
        - title: Features
         labels:
                - feat
        - title: Bug Fixes
         labels:
                - fix
        - title: Major release
         labels:
            - major