changelog:
  exclude:
    labels:
      - chore
      - style
      - major

    authors:
      - NexusWave
  categories:
    - title: Features
      labels:
        - feat

    - title: Bug Fixes
      labels:
        - fix

    - title: Major Changes
      labels:
        - major
